### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Josagulop** [grvcTeam/grvc-ual#19]
In backend_mavros.cpp line 135:

_flight_mode_service.response.success ? "true" : "false");_

**SetMode.Response.success** has been changed to **SetMode.Response.mode_sent**, so it must be:

_flight_mode_service.response.mode_sent ? "true" : "false");_

Source: 
https://github.com/mavlink/mavros/commit/599c5887ad2aadc124d7e1354f3a1597402118da

**Comment by goncalvestiago** [comment]
@arturotorresg 

I'm experiencing the same compiling error with tag v1.5. I've tried several PX4 versions from v1.5.5 till v1.6.5 without success.

Greetings from the Multidrone project

**Comment by arturotorresg** [comment]
We are dealing with this error. The problem is also that the new mavros dependency, GeographicLib, needs to have a file downloaded in order to work. If not, you will compile but you will have an execution error.
