### ISSUE TITLE
Compilation error with latest ros-kinetic version

### ISSUE THREAD

**Issue by Bardo91** [grvcTeam/grvc-ual#21]
catkin_make backtrace

´´´
-- PX4 VERSION: v1.6.3
-- CONFIG: posix-sitl-default
-- CMAKE_INSTALL_PREFIX: /home/bardo91/programming/grvc_catkin/install
-- CMAKE_MODULE_PATH: /home/bardo91/programming/grvc_catkin/src/Firmware/cmake
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- catkin ENABLED
-- Found PY_jinja2: /usr/lib/python2.7/dist-packages/jinja2  
-- C compiler: cc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
-- C++ compiler: c++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
-- +++ processing catkin package: 'px4_bringup'
-- ==> add_subdirectory(grvc-ual/px4_bringup)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'handy_tools'
-- ==> add_subdirectory(grvc-utils/handy_tools)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'uav_abstraction_layer'
-- ==> add_subdirectory(grvc-ual/uav_abstraction_layer)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at grvc-ual/uav_abstraction_layer/CMakeLists.txt:37 (message):
  GeographicLib exception: File not readable
  /usr/share/GeographicLib/geoids/egm96-5.pgm

   Run install_geographiclib_dataset.sh script in order to install Geoid Model dataset! 
   Or run: $ sudo geographiclib-get-geoids egm96-5

-- Configuring incomplete, errors occurred!
See also "/home/bardo91/programming/grvc_catkin/build/CMakeFiles/CMakeOutput.log".
See also "/home/bardo91/programming/grvc_catkin/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
´´´

**Comment by Bardo91** [comment]
Just run `sudo geographiclib-get-geoids egm96-5`.

Addded note in the install guide: https://github.com/grvcTeam/grvc-ual/wiki/How-to-build-and-install-grvc-ual#support-simulation-and-sitl

**Comment by arturotorresg** [comment]
This problem is caused by mavros package with versión v0.20.0 or greater. This new version needs to have installed the geoids for GeographicLib and mavros shows a runtime error. Since this errors are not directly shown in UAL execution, we opted to throw a compile error with the instruction `sudo geographiclib-get-geoids egm96-5` from commit aaffce083b278aac10c9c5c459fc2dc81d37c5b3.
