### ISSUE TITLE
Check possibility of a backend for AirSim

### ISSUE THREAD

**Issue by arturotorresg** [grvcTeam/grvc-ual#24]
https://github.com/Microsoft/AirSim

**Comment by manfer33** [comment]
Tested successfully AirSim for PX4 SITL in Ubuntu 16.04, but with low FPS. Should be there a configuration parameter which can run the simulation lighter

**Comment by arturotorresg** [comment]
Ready since 604c5426cd25614d1a8913981f5eabe98d99a49f.
