### ISSUE TITLE
Issues with installation instructions

### ISSUE THREAD

**Issue by sneheshs** [grvcTeam/grvc-ual#36]
I started a brand new Ubuntu 16.04 with ROS kinetic. Then I followed your instructions. At the very last step, I get the following error message:
Command
`roslaunch uav_abstraction_layer test_server.launch `
Error
```
[test_server.launch] is neither a launch file in package [uav_abstraction_layer] nor is [uav_abstraction_layer] a launch file name
The traceback for the exception was written to the log file
```

Also, the sitl gazebo launcher has issues. The IMU is failing:
```
ERROR [sensors] Accel #0 fail:  TIMEOUT!
ERROR [sensors] Gyro #0 fail:  TIMEOUT!
```

**Comment by sneheshs** [comment]
IMU failure seems like PX4 issues. You can ignore that one.

**Comment by arturotorresg** [comment]
The error with the launch is probably caused by a bad configuration of the [catkin workspace](http://wiki.ros.org/catkin/Tutorials/create_a_workspace). Be sure of sourcing [catkin_ws_folder]/devel/setup.bash and also try to run `rospack profile` and see the list of packages in your workspace.
