### ISSUE TITLE
Manual mode tutorial 

### ISSUE THREAD

**Issue by Zitzo** [grvcTeam/grvc-ual#38]
Hello, I'm looking for the way to control the UAV with a joystick, since the install tutorial talks about this option,  but I can't find any tutorial that explains the way to do it. It would be great if someone could tell me the way.

**Comment by Bardo91** [comment]
There is a package for teleoperation here: https://github.com/grvcTeam/grvc-ual/tree/master/ual_teleop give a look to it.
