### ISSUE TITLE
Check unusual tf frequency rate of the simulator

### ISSUE THREAD

**Issue by edufercab** [grvcTeam/grvc-ual#44]
I was playing with the simulator a bit and by chance I executed the following commands:
$ rosrun tf view_frames
$ evince frames.pdf

The report generated report a transformation rate of 10kHz between map and uav_N_home. I believe that this rate could be somehow consuming much more resources than the necessaries.

Please check!

**Comment by arturotorresg** [comment]
I think that this is an error of the view_frames tool. We use [tf2_ros::StaticTransformBroadcaster](http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20static%20broadcaster%20%28C%2B%2B%29) to publish this transform, you can see it in the /tf_static topic. Thus, the tf view_frames tool may not be prepared to understand these static transforms.
