### ISSUE TITLE
Localization error and tf frames

### ISSUE THREAD

**Issue by margaridaCF** [grvcTeam/grvc-ual#57]
Hi guys!

   I continue happily using ual in my project to communicate with px4. :D

  Recently the world changed, now a localization error now is showing up. In the picture, you can see this error.
![localization_error_highlight](https://user-images.githubusercontent.com/1846072/58121069-723caf00-7bfe-11e9-96e1-c0f499428c13.png)

   **I am wondering if I have linked the frames correctly.**
   The names I get are not the same shown in the wiki, probably because of the version. The equivalent of `/uav_1/mavros/local_position/pose` topic is `uav_1_home` frame?
   The error is a bit strange because the map builds well even after turning. It does a square-shaped flight path well. Only when it turns back for the next waypoints do the problems start. Is there any drifting effect I should be aware of?

   The launch file is [here](https://github.com/margaridaCF/FlyingOctomap_code/blob/20190423_measurements/architecture/launch/px4_ual_powerPlant.launch)

   Here is what I get with `rosrun tf view_frames`
![frames](https://user-images.githubusercontent.com/1846072/58121824-2c80e600-7c00-11e9-91cd-b7cfc6ad68f0.png)

The parameter server has:

PARAMETERS
 * /current_position_topic: /uav_1/mavros/loc...
 * /do_initial_maneuver: True
 * /exploration_maneuver_duration_secs: 18
 * /exploration_maneuver_phases_duration_secs: 5
 * /frontier/safety_margin: 3
 * /geofence_max/x: 30
 * /geofence_max/y: 20
 * /geofence_max/z: 20
 * /geofence_min/x: -30
 * /geofence_min/y: -40
 * /geofence_min/z: 4
 * /odometry_error: 0.1
 * /oppairs/circle_divisions: 4
 * /oppairs/distance_behind: 2
 * /oppairs/distance_inFront: 2
 * /oppairs/sensing_distance: 4
 * /path/max_cycles_waited_for_path: 50
 * /path/max_time_secs: 30
 * /path/safety_margin: 5
 * /px4/flight_speed: 3
 * /px4/yaw_rate: 100
 * /px4_loiter_radius: 1.5
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /scan_filter_chain: [{'type': 'LaserS...
 * /uav/laser_topic: hokuyo_laser_scan
 * /uav_1/ual/home_pose: [0, 0, 0]
 * /uav_1/ual/home_pose_parent_frame: map
 * /uav_1/ual/mavros_offboard_rate: 30.0
 * /uav_1/ual/offboard_enabled: True
 * /uav_1/ual/pose_frame_id: 
 * /uav_1/ual/ual_pub_rate: 30.0
 * /uav_1/ual/ual_server: on
 * /uav_1/ual/uav_id: 1
 * /use_sim_time: True

 I am in commit 5454d77ab249a7231826a47fb3fa6a1ff0865820 at master (11/07/2018). I froze at this version as it was working perfectly for me.

**Comment by arturotorresg** [comment]
Hi Margarida! I know upgrading scares, but you can try the newer versions of UAL which are much better ;P Specifically, we changed the TFs and namespaces to meet ROS standards. Now UAL publishes [ns]/odom and [ns]/base_link TFs.

Regarding your issue, if you have the param /uav_1/ual/home_pose: [0, 0, 0] then /uav_1_home is equal to /map. The pose in /mavros/local_position/pose is relative to the place where PX4 is started, so in this case is both /uav_1_home and /map frames. The PX4 SITL simulates GPS noise, but it is not usual to have a noticeable drift in the local_position filter in simulation. Have you changed the PX4 configuration to accept poses apart from GPS?
