### ISSUE TITLE
Sudden use of rosparam

### ISSUE THREAD

**Issue by franreal** [grvcTeam/grvc-ual#60]
Must be a reason for this...

![rosparam](https://user-images.githubusercontent.com/7678950/62121445-e4e39e00-b2c3-11e9-9de9-234444be25d4.png)

**Comment by arturotorresg** [comment]
rosparam allows the use of vectors. It could be substituted by three params "home_pose_x", "home_pose_y" and "home_pose_z", but then you have two more lines ^_^
