### ISSUE TITLE
Make UAL and child Backends independent to ease new backends creation

### ISSUE THREAD

**Issue by franreal** [grvcTeam/grvc-ual#61]
One simple solution would be to pass Backend pointer to UAL init function and remove init call in constructors. Remove also createBackend function from Backend, as this responsibility is now for programmers.

```
void UAL::init(Backend* _backend) {
    backend_ = _backend;
...
```

**Comment by arturotorresg** [comment]
Ready since [v3.0](https://github.com/grvcTeam/grvc-ual/releases/tag/v3.0).
