### ISSUE TITLE
Review UAL guide - command order to prepare SITL simulation

### ISSUE THREAD

**Issue by manfer33** [grvcTeam/grvc-ual#63]
The section to review is "Compiling PX4" in the following [link](https://github.com/grvcTeam/grvc-ual/wiki/How-to-build-and-install-grvc-ual#support-simulation-and-sitl)

The correct order should be:
```
$ cd ~/catkin_ws/src/Firmware
$ make
$ cd ~/catkin_ws
$ catkin_make
$ cd ~/catkin_ws/src/Firmware
$ make posix_sitl_default gazebo
$ cd ~/catkin_ws
$ catkin_make
```

Additionally, has the last command any usefulness?

**Comment by arturotorresg** [comment]
Solved ;)
